behaviors:
  FortniteAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 1.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    summary_freq: 10000
    max_steps: 1e7 # 10 million
    time_horizon: 64

environment_parameters:
  aim_bonus:
    curriculum:
      - name: WithFullAimBonus
        completion_criteria:
          measure: reward
          behavior: FortniteAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 3.5
        value: 1
      - name: WithHalfAimBonus
        completion_criteria:
          measure: reward
          behavior: FortniteAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 3
        value: 0.5
      - name: WithoutAimBonus
        value: 0